export const planets = {
	mercury: {
		orbitSpeed: 0.00048,
		orbitRadius: 10,
		orbitRotationDirection: 'clockwise',
		planetSize: 0.2,
		planetRotationSpeed: 0.005,
		planetRotationDirection: 'counterclockwise',
		rimHex: 0xf9cf9f,
		ringsSize: 0,
		planetAngle: 0,
	},
	venus: {
		orbitSpeed: 0.00035,
		orbitRadius: 13,
		orbitRotationDirection: 'clockwise',
		planetSize: 0.5,
		planetRotationSpeed: 0.0005,
		planetRotationDirection: 'clockwise',
		rimHex: 0xb66f1f,
		ringsSize: 0,
		planetAngle: 0,
	},
	earth: {
		orbitSpeed: 0.00029,
		orbitRadius: 16,
		orbitRotationDirection: 'clockwise',
		planetSize: 0.5,
		planetAngle: (-23.4 * Math.PI) / 180,
		planetRotationSpeed: 0.01,
		planetRotationDirection: 'counterclockwise',
		rimHex: 0x0088ff,
		ringsSize: 0,
	},
	mars: {
		orbitSpeed: 0.00024,
		orbitRadius: 19,
		orbitRotationDirection: 'clockwise',
		planetSize: 0.3,
		planetRotationSpeed: 0.01,
		planetRotationDirection: 'counterclockwise',
		rimHex: 0xbc6434,
		ringsSize: 0,
		planetAngle: 0,
	},
	jupiter: {
		orbitSpeed: 0.00013,
		orbitRadius: 22,
		orbitRotationDirection: 'clockwise',
		planetSize: 1,
		planetRotationSpeed: 0.06,
		planetRotationDirection: 'counterclockwise',
		rimHex: 0xf3d6b6,
		ringsSize: 0,
		planetAngle: 0,
	},
	saturn: {
		orbitSpeed: 0.0001,
		orbitRadius: 25,
		orbitRotationDirection: 'clockwise',
		planetSize: 0.8,
		planetRotationSpeed: 0.05,
		planetRotationDirection: 'counterclockwise',
		rimHex: 0xd6b892,
		ringsSize: 0.5,
		planetAngle: 0,
	},
	uranus: {
		orbitSpeed: 0.00007,
		orbitRadius: 28,
		orbitRotationDirection: 'clockwise',
		planetSize: 0.5,
		planetRotationSpeed: 0.02,
		planetRotationDirection: 'clockwise',
		rimHex: 0x9ab6c2,
		ringsSize: 0.4,
		planetAngle: 0,
	},
	neptune: {
		orbitSpeed: 0.000054,
		orbitRadius: 31,
		orbitRotationDirection: 'clockwise',
		planetSize: 0.5,
		planetRotationSpeed: 0.02,
		planetRotationDirection: 'counterclockwise',
		rimHex: 0x5c7ed7,
		ringsSize: 0,
		planetAngle: 0,
	},
} as const;

export const planetNames = Object.keys(planets) as (keyof typeof planets)[];
